"""paper orders and ledger events

Revision ID: 8ee7ba57d575
Revises: bc96a34fe8fd
Create Date: 2026-10-02 22:18:54.901008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ee7ba57d575'
down_revision: Union[str, Sequence[str], None] = 'bc96a34fe8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_events',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('data_label', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_ledger_events_event_key'), 'ledger_events', ['event_key'], unique=False)
    op.create_index(op.f('ix_ledger_events_mode'), 'ledger_events', ['mode'], unique=False)
    op.create_index(op.f('ix_ledger_events_run_id'), 'ledger_events', ['run_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('data_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_paper_orders_mode'), 'paper_orders', ['mode'], unique=False)
    op.create_index(op.f('ix_paper_orders_order_id'), 'paper_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_run_id'), 'paper_orders', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_orders_run_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_order_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_mode'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_ledger_events_run_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_mode'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_event_key'), table_name='ledger_events')
    op.drop_table('ledger_events')
    # ### end Alembic commands ###
