"""initial canonical record tables

Revision ID: bc96a34fe8fd
Revises: 
Create Date: 2026-10-02 21:57:34.929834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc96a34fe8fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('strategy_version', sa.String(length=80), nullable=False),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_decisions_action'), 'decisions', ['action'], unique=False)
    op.create_index(op.f('ix_decisions_decision_id'), 'decisions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decisions_decision_time'), 'decisions', ['decision_time'], unique=False)
    op.create_index(op.f('ix_decisions_game_id'), 'decisions', ['game_id'], unique=False)
    op.create_table('game_states',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_game_states_game_id'), 'game_states', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_states_snapshot_id'), 'game_states', ['snapshot_id'], unique=False)
    op.create_table('games',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('sport', sa.String(length=8), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=False)
    op.create_table('llm_reviews',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_llm_reviews_decision_id'), 'llm_reviews', ['decision_id'], unique=False)
    op.create_index(op.f('ix_llm_reviews_review_id'), 'llm_reviews', ['review_id'], unique=False)
    op.create_table('market_mappings',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mapping_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('contract_id', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_market_mappings_game_id'), 'market_mappings', ['game_id'], unique=False)
    op.create_index(op.f('ix_market_mappings_mapping_id'), 'market_mappings', ['mapping_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_model_versions_model_version'), 'model_versions', ['model_version'], unique=False)
    op.create_table('paper_fills',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('fill_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_paper_fills_fill_id'), 'paper_fills', ['fill_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_game_id'), 'paper_fills', ['game_id'], unique=False)
    op.create_table('predictions',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_predictions_game_id'), 'predictions', ['game_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=False)
    op.create_table('raw_events',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('raw_id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_raw_events_raw_id'), 'raw_events', ['raw_id'], unique=False)
    op.create_index(op.f('ix_raw_events_received_time'), 'raw_events', ['received_time'], unique=False)
    op.create_index(op.f('ix_raw_events_source'), 'raw_events', ['source'], unique=False)
    op.create_table('settlements',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('settlement_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_settlements_game_id'), 'settlements', ['game_id'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_id'), 'settlements', ['settlement_id'], unique=False)
    op.create_table('sportsbook_quotes',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=80), nullable=False),
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('provider_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_sportsbook_quotes_game_id'), 'sportsbook_quotes', ['game_id'], unique=False)
    op.create_index(op.f('ix_sportsbook_quotes_quote_id'), 'sportsbook_quotes', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sportsbook_quotes_quote_id'), table_name='sportsbook_quotes')
    op.drop_index(op.f('ix_sportsbook_quotes_game_id'), table_name='sportsbook_quotes')
    op.drop_table('sportsbook_quotes')
    op.drop_index(op.f('ix_settlements_settlement_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_game_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_raw_events_source'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_received_time'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_raw_id'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_game_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_paper_fills_game_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_fill_id'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_model_versions_model_version'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_market_mappings_mapping_id'), table_name='market_mappings')
    op.drop_index(op.f('ix_market_mappings_game_id'), table_name='market_mappings')
    op.drop_table('market_mappings')
    op.drop_index(op.f('ix_llm_reviews_review_id'), table_name='llm_reviews')
    op.drop_index(op.f('ix_llm_reviews_decision_id'), table_name='llm_reviews')
    op.drop_table('llm_reviews')
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_states_snapshot_id'), table_name='game_states')
    op.drop_index(op.f('ix_game_states_game_id'), table_name='game_states')
    op.drop_table('game_states')
    op.drop_index(op.f('ix_decisions_game_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_time'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_action'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
